language: android
android:
 components:
    - build-tools-19.1
    - android-19
    - sysimg-19
    - extra-android-support

branches:
  only:
    - dev
    - master

jdk: oraclejdk7

env:
  global:
    - ANDROID_SDK_VERSION="r22.6.2"

notifications:
  email: true


